import Head from 'next/head'
import React from 'react'
import footerSheet from '../styles/footer.module.scss'

export default function Footer() {
    return (
        <>
            <Head>
            <meta charset='UTF-8'/>
            <meta name="description" content="Generated by create next app" />
            </Head>

            <div className={footerSheet.container}>
                <h1 className={footerSheet.arrow}>↑</h1>
            </div>
        </>
    );
}