import Head from 'next/head'
import React from 'react'
import headerSheet from '../styles/header.module.scss'

export default function Header() {
    return (
        <>
            <Head>
            <meta charset='UTF-8'/>
            <meta name="description" content="Generated by create next app" />
            </Head>

            <div className={headerSheet.container}>
                <h1 className={headerSheet.titleLeft}>broom</h1>
                <div className={headerSheet.titleRight}>
                    <h3>Ja</h3> 
                    <h3>En</h3> 
                    <a>三</a>
                </div>
            </div>
        </>
    );
}