import Head from 'next/head'
import React from 'react'
import headerSheet from '../styles/header.module.scss'

export default function Header() {
    return (
        <>
            <Head>
            <meta charset='UTF-8'/>
            <meta name="description" content="Generated by create next app" />
            </Head>

            <div className={headerSheet.container}>
                <div className={headerSheet.titleLeft}>
                    <img className={headerSheet.title} src="/image/broom.svg"/>
                </div>
                <ul className={headerSheet.titleRight}>
                    <li className={headerSheet.group}>
                        <a href='/' className={`${headerSheet.subtitle} ${headerSheet.select}`}>Ja</a> 
                        <a href='/' className={`${headerSheet.subtitle} ${headerSheet.select}`}>En</a> 
                    </li>
                    <li className={headerSheet.group}>
                        <a href='/' className={headerSheet.menu}>
                        <span></span>
                        <span></span>
                        <span></span>
                        </a>
                    </li>
                </ul>
            </div>
        </>
    );
}