import Head from 'next/head'
import React from 'react'
import headerSheet from '../styles/header.module.scss'

export default function Header() {
    return (
        <>
            <Head>
            <meta charset='UTF-8'/>
            <meta name="description" content="Generated by create next app" />
            </Head>

            <div className={headerSheet.container}>
                <div className={headerSheet.titleLeft}>
                    <h1 className={headerSheet.title}>broom</h1>
                </div>
                <div className={headerSheet.titleRight}>
                    <a href='/' className={headerSheet.subtitleJa}>Ja</a> 
                    <a href='/' className={headerSheet.subtitleEn}>En</a> 
                    <a href='/' className={headerSheet.subtitle}>三</a>
                </div>
            </div>
        </>
    );
}