import Head from 'next/head'
import React from 'react'
import iconsSheet from '../styles/icons.module.scss'

export default function Icons() {
    return (
        <>
            <Head>
            <meta charset='UTF-8'/>
            <meta name="description" content="Generated by create next app" />
            </Head>

            <div className={iconsSheet.container}>
                <div className={iconsSheet.item}>
                    <h5 className={iconsSheet.text}>We design</h5>
                    <img className={iconsSheet.img} src="/image/top_icons_a.gif"/>
                </div>
                <div className={iconsSheet.item}>
                    <h5 className={iconsSheet.text}>Integrate for</h5>
                    <img className={iconsSheet.img} src="/image/top_icons_b.gif"/>
                </div>
            </div>
        </>
    );
}