import Head from 'next/head'
import React from 'react'
import newsSheet from '../styles/news.module.scss'

export default function News() {
    return (
        <>
            <Head>
            <meta charset='UTF-8'/>
            <meta name="description" content="Generated by create next app" />
            </Head>

            <h3>Recent news</h3>
            <img src="/image/j_012.jpg"/>
            <p>2020.12 / Award</p>
            <p>DFAアジアデザイン賞2020（香港）にて、broom inc.でクリエイティブ全般を手掛けた「12/JU-NI」がコミュニケーションデザイン部門からBronze Award、「Parcel」がインダストリアルデザイン部門からMerit Awardを、それぞれ受賞しました。</p>
            <a href=''>DFA AWARDS</a>
            <img src="/image/j_010.jpg"/>
            <p>2020.07 / Launch</p>
            <p>訪日外国人の防災をサポートするプロジェクトを立ち上げました。（運営・プロジェクトオーナー : 株式会社ヒロモリ Fun to BOSAI Unit / 事業開発支援・クリエイティブディレクション : broom inc. ）</p>
            <a href=''>BOSAI UNISON PROJECT</a>

        </>
    );
}