import Head from 'next/head'
import React from 'react'
import newsSheet from '../styles/news.module.scss'

export default function News() {
    return (
        <>
            <Head>
            <meta charset='UTF-8'/>
            <meta name="description" content="Generated by create next app" />
            </Head>

            <div className={newsSheet.container}>
                <h3 className={newsSheet.title}>Recent news</h3>
                <div className={newsSheet.item}>
                    <img className={newsSheet.img} src="/image/j_012.jpg"/>
                    <div className={newsSheet.itemText}>
                        <p className={newsSheet.text}>2020.12 / Award</p><br/>
                        <p className={newsSheet.text}>DFAアジアデザイン賞2020（香港）にて、broom inc.でクリエイティブ全般を手掛けた「12/JU-NI」がコミュニケーションデザイン部門からBronze Award、「Parcel」がインダストリアルデザイン部門からMerit Awardを、それぞれ受賞しました。</p>
                        <a href='' className={newsSheet.textUrl}>DFA AWARDS</a>
                    </div>
                </div>
                <div className={newsSheet.item}>
                    <img className={newsSheet.img} src="/image/j_010.jpg"/>
                    <div className={newsSheet.itemText}>
                        <p className={newsSheet.text}>2020.07 / Launch</p><br/>
                        <p className={newsSheet.text}>訪日外国人の防災をサポートするプロジェクトを立ち上げました。（運営・プロジェクトオーナー : 株式会社ヒロモリ Fun to BOSAI Unit / 事業開発支援・クリエイティブディレクション : broom inc. ）</p>
                        <a href='' className={newsSheet.textUrl}>BOSAI UNISON PROJECT</a>
                    </div>
                </div>
            </div>

        </>
    );
}