import Head from 'next/head'
import React from 'react'
import topSheet from '../styles/top.module.scss'

export default function Top() {
    return (
        <>
            <Head>
            <meta charset='UTF-8'/>
            <meta name="description" content="Generated by create next app" />
            </Head>

            <div className={topSheet.container}>
                <img className={topSheet.img} src="/image/cover_14.jpg"/>
                <div className={topSheet.textScroll}>
                    <p className={topSheet.border}>Scroll Down</p>
                </div>
                <div className={topSheet.text}>
                    <p>Products,brands,and experiences.</p>
                    <a href='/' className={topSheet.Url}>
                        <img className={topSheet.img} src="/image/arrow-2.svg"/>
                        <span className={topSheet.UrlText}>See work archive</span>
                    </a>
                </div>
            </div>
        </>
    );
}