import Head from 'next/head'
import React from 'react'
import usSheet from '../styles/us.module.scss'

export default function Us() {
    return (
        <>
            <Head>
            <meta charset='UTF-8'/>
            <meta name="description" content="Generated by create next app" />
            </Head>

            <h3>About us</h3>
            <p>broom inc.は東京を拠点に活動するデザインスタジオ。モノの企画・設計、ブランディング、事業開発まで、デザインを軸に、だいたいなんでもやっています。多様で複雑な現代のブランドやサービス、延いては物事の構造に合わせて、やわらかくいちばんいい”カタチ”を模索し、価値の高いアウトプットを実現します。</p>
            <a href=''>→ Learn more</a>
            <img src="/image/top_ven.svg"/>

        </>
    );
}