import Head from 'next/head'
import React, {useState, useRef}  from 'react'
import Header from '../components/common/Header'
import Nav from '../components/common/Nav'
import Contact from '../components/contact/Contact'
import Footer from '../components/common/Footer'
import Arrow from '../components/common/Arrow'


export default function contact() {
  const [show, setShow] = useState(false)
  const modal = useRef()
  const Open = () => {
      if(show==false){
          setShow(true)
      }
      else if(show==true){
          setShow(false)
      }
      else{
          return null;
      }
  }
  return (
    <>
      <Head>
        <meta charset='UTF-8'/>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Nav show={show}/>
      <Header Open={Open} show={show}/>
      <Contact/>
      <Footer/>
      <Arrow/>

    </>
  )
}
