import Head from 'next/head'
import React, {useState, useRef}  from 'react'
import Header from '../components/Header'
import Modal from '../components/Modal'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import Nav from '../components/Nav'


export default function contact() {
  const [show, setShow] = useState(false)
  const modal = useRef()
  const Open = () => {
      if(show==false){
          setShow(true)
      }
      else if(show==true){
          setShow(false)
      }
      else{
          return null;
      }
  }
  return (
    <>
      <Head>
        <meta charset='UTF-8'/>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Modal show={show}/>
      <Header Open={Open} show={show}/>
      <Contact/>
      <Footer/>
      <Nav/>

    </>
  )
}
