import Head from 'next/head'
import React from 'react'
import indexSheet from '../styles/index.module.scss'
import Header from '../components/Header'
import Top from '../components/Top'
import Icons from '../components/Icons'
import Us from '../components/Us'
import News from '../components/News'
import Projects from '../components/Projects'

export default function index() {
  return (
    <>
      <Head>
        <meta charset='UTF-8'/>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header/>
      <Top/>
      <Icons/>
      <Us/>
      <News/>
      <Projects/>
      <p className={indexSheet.text}>©broom inc.all rights reserved.</p>
    </>
  )
}
