import Head from 'next/head'
import { gsap } from "gsap";
import { ScrollToPlugin } from "gsap/dist/ScrollToPlugin";
import React, {useState, useRef}  from 'react';
import Header from '../components/common/Header'
import Top from '../components/index/Top'
import Icons from '../components/index/Icons'
import About from '../components/index/About'
import Newses from '../components/index/Newses'
import Projects from '../components/index/Projects'
import Footer from '../components/common/Footer'
import Arrow from '../components/common/Arrow'
import Nav from '../components/common/Nav'

// gsapでscrollToを使用するために必須
gsap.registerPlugin(ScrollToPlugin);

export default function index() {
  const [show, setShow] = useState(false)
  // const modal = useRef()
  // const window = useRef()
  const Open = () => {
    if(show==false){
        setShow(true)
    }
    else if(show==true){
        setShow(false)
    }
    else{
        return null;
    }
  }
  const scrollTop = (e) => {
    // イベントをキャンセル
    e.preventDefault()
    // windowはグローバル変数
    gsap.to(window, {
      duration: 2,
      scrollTo: {y: 0},
    })
  }
  return (
    <>
      <Head>
        <meta charset='UTF-8'/>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav show={show}/>
      <Header Open={Open} show={show}/>
      <Top/>
      <Icons/>
      <About/>
      <Newses/>
      <Projects/>
      <Footer/>
      <Arrow scrollTop={scrollTop}/>
    </>
  )
}
