import Head from 'next/head'
import React, {useState, useRef}  from 'react'
import Header from '../components/Header'
import Top from '../components/Top'
import Icons from '../components/Icons'
import About from '../components/About'
import Newses from '../components/Newses'
import Projects from '../components/Projects'
import Footer from '../components/Footer'
import Nav from '../components/Nav'
import Modal from '../components/Modal'

export default function index() {
  const [show, setShow] = useState(false)
  const modal = useRef()
  const Open = () => {
      if(show==false){
          setShow(true)
      }
      else if(show==true){
          setShow(false)
      }
      else{
          return null;
      }
  }
  return (
    <>
      <Head>
        <meta charset='UTF-8'/>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Modal show={show}/>
      <Header Open={Open} show={show}/>
      <Top/>
      <Icons/>
      <About/>
      <Newses/>
      <Projects/>
      <Footer/>
      <Nav/>
    </>
  )
}
